// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCietrlj8fidBhHuRgjSvA1cpxTz1PgWPE',
    appId: '1:156632910258:web:b139f06f84dd7fadc0fcab',
    messagingSenderId: '156632910258',
    projectId: 'donvital',
    authDomain: 'donvital.firebaseapp.com',
    storageBucket: 'donvital.appspot.com',
    measurementId: 'G-B8EJD941HH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLc3xKVolM39zjHHqDYmNORHmAEsKtXK8',
    appId: '1:156632910258:android:00fbaf6fcaf0d83ac0fcab',
    messagingSenderId: '156632910258',
    projectId: 'donvital',
    storageBucket: 'donvital.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKufhAF-CEAv42tTmU3LSFx5IEx526Qsw',
    appId: '1:156632910258:ios:fb613553ae31b257c0fcab',
    messagingSenderId: '156632910258',
    projectId: 'donvital',
    storageBucket: 'donvital.appspot.com',
    iosBundleId: 'com.example.bloodDonnation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKufhAF-CEAv42tTmU3LSFx5IEx526Qsw',
    appId: '1:156632910258:ios:fb613553ae31b257c0fcab',
    messagingSenderId: '156632910258',
    projectId: 'donvital',
    storageBucket: 'donvital.appspot.com',
    iosBundleId: 'com.example.bloodDonnation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCietrlj8fidBhHuRgjSvA1cpxTz1PgWPE',
    appId: '1:156632910258:web:624f3a2b7e0b5543c0fcab',
    messagingSenderId: '156632910258',
    projectId: 'donvital',
    authDomain: 'donvital.firebaseapp.com',
    storageBucket: 'donvital.appspot.com',
    measurementId: 'G-DDQ6FHXP2S',
  );
}
